### ISSUE TITLE
Drop or vendor dj_database_url

### ISSUE THREAD

**Issue by 1oglop1** [joshourisman/django-pydantic-settings#33]
Hi, I was just searched for `django pydantic settings` and found this.
The reason I searched was that many django projects reading environment variables are not maintained or did not release the changes.

`dj_database_url` is version 0.5 and renders wrong db engine. `postgresql_psycopg2` jacobian/dj-database-url#131 - which according to comments had been fixed in the master but not released.

I abandoned `dj_database_url` for `django-environ` which I found out suffering from the same problem (not releasing) joke2k/django-environ#282

**Comment by joshourisman** [comment]
Huh, I'll have to take a look at that. I'm using postgis for basically everything, which is probably why I hadn't caught that.
